name: Sync Main to GH Pages

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main
      - copilot/copy-files-to-gh-pages  # For testing

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages:gh-pages || git checkout -b gh-pages
      
      - name: Switch to gh-pages branch
        run: git checkout gh-pages
      
      - name: Remove old files (except .git)
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
      
      - name: Copy files from main branch
        run: |
          git checkout origin/main -- .
      
      - name: Commit and push changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync files from main branch"
            git push origin gh-pages
          fi
